In [2]:
# import required libraries
import numpy as np
import pandas as pd

In [6]:
data = 'C:/datasets/forestfires.csv'
df = pd.read_csv(data)


In [8]:
# View the first five rows of dataset
df.head()

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In this project, I will analyze this dataset using NumPy, which is a commonly used Python data analysis package.

I will extract the last 5 variables - temp(temperature), RH(relative humidity), wind(wind speed), rain(rain) and

area(area) into a new dataset fires. I will also extract the first five rows of dataset as follws:

In [9]:
fires = df.iloc[:5,8:]

print(fires)

   temp  RH  wind  rain  area
0   8.2  51   6.7   0.0   0.0
1  18.0  33   0.9   0.0   0.0
2  14.6  33   1.3   0.0   0.0
3   8.3  97   4.0   0.2   0.0
4  11.4  99   1.8   0.0   0.0


# NumPy ndarray object

The most important object defined in NumPy is an N-dimensional array called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index. Each element in ndarray is an object of data-type object (called dtype).

In [10]:
# one dimensional array

a = np.array([1,2,3])

print(a)

[1 2 3]


In [11]:
# continuing with our fires dataset, we can extract first row of fires and 
# transform into a 1-D array as follows:-

n1 = np.array(fires[:1])

print(n1)

[[ 8.2 51.   6.7  0.   0. ]]


In [12]:
# two dimensional array

b = np.array([[1, 2], [3, 4]])

print(b)

[[1 2]
 [3 4]]


In [13]:
# three dimensional array

c = np.array([[1,2],[3,4],[5,6]])

print(c)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
# following along with the fires dataset, a three dimensional array of the 
# fires dataset with integer data types can be created as follows

n3 = np.array(fires[:3], dtype=int)

print(n3)

[[ 8 51  6  0  0]
 [18 33  0  0  0]
 [14 33  1  0  0]]


In [15]:
# minimum dimensions 

d = np.array([1, 2, 3, 4, 5], ndmin = 2)

print(d)

[[1 2 3 4 5]]


In [16]:
# dtype parameter 

e = np.array([1, 2, 3], dtype = complex) 

print(e)

[1.+0.j 2.+0.j 3.+0.j]


# NumPy data types

NumPy supports a much greater variety of numerical data types than Python. The following table shows most common data types defined in NumPy.

bool_ - Boolean (True or False) stored as a byte

int_ - Default integer type (same as C long; normally either int64 or int32)

intc - Identical to C int (normally int32 or int64)

intp - Integer used for indexing (same as C ssize_t; normally either int32 or int64)

int8 - Byte (-128 to 127)

int16 - Integer (-32768 to 32767)

int32 - Integer (-2147483648 to 2147483647)

int64 - Integer (-9223372036854775808 to 9223372036854775807)

float_ - Shorthand for float64

float16 - Half precision float: sign bit, 5 bits exponent, 10 bits mantissa

float32 - Single precision float: sign bit, 8 bits exponent, 23 bits mantissa

float64 - Double precision float: sign bit, 11 bits exponent, 52 bits mantissa

# NumPy array attributes

In this section, I will discuss the various NumPy array attributes. The attributes are ndarray.shape, ndarray.size, ndarray.ndim, ndarray.itemsize, ndarray.dtype and ndarray.data.

# ndarray.shape

In [17]:
x1 = np.array([[1,2,3],[4,5,6]]) 

print(x1.shape)

(2, 3)


In [18]:
# check the shape of the n1 array

print(n1.shape)

(1, 5)


In [21]:
# resizes the ndarray 

x2 = np.array([[1,2,3],[4,5,6]])

x2.shape = (3,2) 

print(x2) 

[[1 2]
 [3 4]
 [5 6]]


# ndarray.size
It returns the total number of elements of the array. This is equal to the product of the elements of shape.

In [22]:
# print the size of the x1 array

print(x1.size)


6


In [23]:
# check the size of the n1 array

print(n1.size)

5


# reshape function
NumPy also provides a reshape function to resize an array.

In [24]:
x1 = np.array([[1,2,3],[4,5,6]])

x1_reshaped = x1.reshape(3,2)

print(x1_reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [25]:
# reshape the n3 array

n3 = n3.reshape(5,3)

print(n3)

[[ 8 51  6]
 [ 0  0 18]
 [33  0  0]
 [ 0 14 33]
 [ 1  0  0]]


# ndarray.ndim
This array attribute returns the number of axes (dimensions) of the array.

In [26]:
# create an array of evenly spaced numbers 

x3 = np.arange(24) 

print(x3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [27]:
# reshape the above array

x4 = x3.reshape(2,4,3) 

print(x4)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [28]:
# check the dimension of n1 array

print(n1.ndim)

2


 # ndarray.itemsize
This array attribute returns the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

In [29]:
# dtype of array is int8 (1 byte) 
 
x5 = np.array([1,2,3,4,5], dtype = np.int8)

print(x5.itemsize)

1


In [30]:
# dtype of array is now float32 (4 bytes) 

x6 = np.array([1,2,3,4,5], dtype = np.float32) 

print(x6.itemsize)

4


# ndarray.dtype
It represents an object describing the type of the elements in the array. We can create or specify dtype’s using standard Python types. Additionally NumPy provides its own dtypes as follows:-

numpy.int32, numpy.int16 and numpy.float64.

In [32]:
print(x5.dtype.name)
print(x6.dtype.name)
# check the dtype of the n1 array
print(n1.dtype.name)

# check the dtype of the n3 array
print(n3.dtype.name)

int8
float32
float64
int32


# type of array
We can check the type of the array with the type() function.

In [33]:
# check type of n1, n3 array
type(n1)
type(n3)

numpy.ndarray

# NumPy array creation
A new ndarray object can be constructed by any of the following array creation routines. There are several ways to create arrays. These are listed below:-

array function

empty function

zeros function

ones function

arange function

linspace function

# array function
We can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [35]:
# create an array

x7 = np.array([2,3,4])

x7


array([2, 3, 4])

In [36]:
# check its dtype

x7.dtype

dtype('int32')

In [37]:
x8 = np.array([1.2, 3.5, 5.1])

x8.dtype

dtype('float64')

# empty function
The function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

The following code shows an example of an empty array:-

In [38]:
x9 = np.empty([2,3], dtype = int) 

print(x9)

[[  7536700   7471220   7209065]
 [  4063335    131072 284166145]]


# zeros function
The function zeros creates an array full of zeros. By default, the dtype of the created array is float.

The following examples demonstrate the use of the zeros function:-

In [39]:
# array of five zeros

x10 = np.zeros(5) 

print(x10)

[0. 0. 0. 0. 0.]


# ones function
The function ones creates an array full of ones. The default dtype is float.

In [41]:
x12 = np.ones(5)

print(x12)

[1. 1. 1. 1. 1.]


In [42]:
# dtype can also be specified

x13 = np.ones([2,2], dtype=int)

print(x13)

[[1 1]
 [1 1]]


# arange function
The arange function creates sequences of numbers. It is analogous to range that returns arrays instead of lists.

In [43]:
x14 = np.arange(10, 20, 2)

print(x14)

[10 12 14 16 18]


In [44]:
# arange function with float arguments

x15 = np.arange(10, 20, 0.5)

print(x15)

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5]


When arange function is used with floating point arguments, it is not possible to predict the number of elements obtained, due to the finite floating point precision. So, it is better to use the linspace function that accepts the number of elements argument that we want, instead of the step.

# linspace function
It returns evenly spaced numbers over a specified interval. The endpoint of the interval can optionally be excluded :-

In [45]:
x16 = np.linspace(2.0, 4.0, num=5)

print(x16)

[2.  2.5 3.  3.5 4. ]


In [46]:
x17 = np.linspace(2.0, 4.0, num=5, endpoint=False)

print(x17)

[2.  2.4 2.8 3.2 3.6]


# Basic slicing
Basic slicing is an extension of Python's basic concept of slicing to n dimensions. A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function. This slice object is passed to the array to extract a part of an array.

In [49]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
s=slice(2,7,2)

In [52]:
print(x[s])

[2 4 6]


In [57]:
arr=np.array([[1,2,3],[3,4,5],[5,6,7]])
arr

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [60]:
arr[1:,0:]

array([[3, 4, 5],
       [5, 6, 7]])

In [62]:
arr[0:,1:2]

array([[2],
       [4],
       [6]])

In [67]:
my_array=np.array(
   [
        [["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"]],
        [["J", "K", "L"], ["M", "N", "O"], ["P", "Q", "S"]],
        [["T", "U", "V"], ["W", "X", "Y"], ["Z", "AA", "AB"]],
    ]
)

In [68]:
my_array

array([[['A', 'B', 'C'],
        ['D', 'E', 'F'],
        ['G', 'H', 'I']],

       [['J', 'K', 'L'],
        ['M', 'N', 'O'],
        ['P', 'Q', 'S']],

       [['T', 'U', 'V'],
        ['W', 'X', 'Y'],
        ['Z', 'AA', 'AB']]], dtype='<U2')

In [85]:
my_name=my_array[0,0,0]+my_array[0,0,0]+my_array[0,1,0]+my_array[0,2,2]+my_array[1,0,2]

In [86]:
my_name

'AADIL'

# NumPy Broadcasting
In NumPy, broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

However, if the dimensions of two arrays are dissimilar, element-to-element operations are not possible. Operations on arrays of different shapes is still possible in NumPy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shapes.

Rules of broadcasting are as follows:-
Array with smaller ndim than the other is prepended with '1' in its shape.
Size in each dimension of the output shape is maximum of the input sizes in that dimension.
An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly 1.
If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that dimension.
A set of arrays is said to be broadcastable if the above rules produce a valid result and one of the following is true:−

Arrays have exactly the same shape.
Arrays have the same number of dimensions and the length of each dimension is either a common length or 1.
Array having too few dimensions can have its shape prepended with a dimension of length 1, so that the above stated property is true.

In [87]:
l1 = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])

l2 = np.array([1.0,2.0,3.0])  
   
print('First array:')
print(l1)
print('\n')
print("The dimension of first array is {}".format(l1.ndim))
print('\n')
   
print('Second array:') 
print(l2)
print('\n')
print("The dimension of second array is {}".format(l2.ndim))
print('\n') 
   
print('First Array + Second Array')
print(l1 + l2)
print('\n')
print("The dimension of first array + second array is {}".format((l1+l2).ndim))

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


The dimension of first array is 2


Second array:
[1. 2. 3.]


The dimension of second array is 1


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


The dimension of first array + second array is 2


In [90]:
array1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])


print(array1.shape)
print(array2.shape)

(1, 10)
(10, 1)


In [91]:
print(array1 * array2)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


# NumPy String Functions
The following functions are used to perform vectorized string operations for arrays of dtype numpy.string_ or numpy.unicode_. They are based on the standard string functions in Python's built-in library.

add() - Returns element-wise string concatenation for two arrays of str or Unicode

multiply() - Returns the string with multiple concatenation, element-wise

center() - Returns a copy of the given string with elements centered in a string of specified length

capitalize() - Returns a copy of the string with only the first character capitalized

title() - Returns the element-wise title cased version of the string or unicode

lower() - Returns an array with the elements converted to lowercase

upper() - Returns an array with the elements converted to uppercase

split() - Returns a list of the words in the string, using separatordelimiter

splitlines() - Returns a list of the lines in the element, breaking at the line boundaries

strip() - Returns a copy with the leading and trailing characters removed

join() - Returns a string which is the concatenation of the strings in the sequence

replace() - Returns a copy of the string with all occurrences of substring replaced by the new string

decode() - Calls str.decode element-wise

encode() - Calls str.encode element-wise

# NumPy Arithmetic Operations
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

Input arrays for performing arithmetic operations such as add(), subtract(), multiply(), and divide() must be either of the same shape or should conform to array broadcasting rules.

In [93]:
radii = np.array([1, 2, 3])
#Area of a circle
print(np.pi * radii**radii)

array1 = np.array([4, 5, 6])
array2 = np.array([7, 8, 9])

# Element wise arithemetic opertaions:
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1**array2)




[ 3.14159265 12.56637061 84.82300165]
[11 13 15]
[-3 -3 -3]
[28 40 54]
[0.57142857 0.625      0.66666667]
[   16384   390625 10077696]


In [94]:
# Comparision operators : Returns True if the condition is met

scores = np.array([56, 78, 100, 45, 86])
# print(scores >= 60)
# print(scores == 100)
# print(scores < 70)

# Alternatively,
# If the score is less than 60, We are assigning it to 0 as fail
scores[scores < 60] = 0
print(scores)

[  0  78 100   0  86]


# NumPy Statistical Functions

NumPy has various useful statistical functions for finding minimum, maximum, percentile, standard deviation and variance, from the given elements in the array.

These functions are explained as follows:−

numpy.amin() and numpy.amax()

These functions return the minimum and the maximum from the elements in the given array along the specified axis.

For rows, axis = 1

For columns, axis = 0

In [96]:
arr= np.array([[5,2,3],[1,5,6],[3,7,4]]) 

arr

array([[5, 2, 3],
       [1, 5, 6],
       [3, 7, 4]])

In [97]:
print('Applying amin() function across rows:') 

print(np.amin(arr,1)) 

Applying amin() function across rows:
[2 1 3]


In [98]:
print('Applying amin() function across columns:') 

print(np.amin(arr,0))

Applying amin() function across columns:
[1 2 3]


In [99]:
print('Applying amax() function across rows:') 

print(np.amax(arr,1)) 

Applying amax() function across rows:
[5 6 7]


In [100]:
print('Applying amax() function across columns:') 

print(np.amax(arr,0))

Applying amax() function across columns:
[5 7 6]


# numpy.ptp()
The numpy.ptp() function returns the range (maximum-minimum) of values along an axis.

In [101]:
print('Applying ptp() function:')

print(np.ptp(arr))


Applying ptp() function:
6


In [102]:
print('Applying ptp() function along rows:')

print(np.ptp(arr, axis = 1))

Applying ptp() function along rows:
[3 5 4]


In [103]:
print('Applying ptp() function along columns:')

print(np.ptp(arr, axis = 0))

Applying ptp() function along columns:
[4 5 3]


# numpy.percentile()
Percentile is a measure used in statistics indicating the value below which a given percentage of observations in a group of observations fall.

In [104]:
# create an array

i2 = np.array([[20,50,80],[30,60,90],[40,70,100]]) 

print(i2)

[[ 20  50  80]
 [ 30  60  90]
 [ 40  70 100]]


In [105]:
print('Applying percentile() function:')

print(np.percentile(i2,50))

Applying percentile() function:
60.0


In [106]:
print('Applying percentile() function along rows:')

print(np.percentile(i2,50,axis = 1))

Applying percentile() function along rows:
[50. 60. 70.]


In [107]:
print('Applying percentile() function along columns:')

print(np.percentile(i2,50,axis = 0))

Applying percentile() function along columns:
[30. 60. 90.]


# numpy.median()
Median is defined as the value separating the higher half of a data sample from the lower half. The numpy.median() function is used as shown in the following program.

In [108]:
# print i2 array

print(i2)

[[ 20  50  80]
 [ 30  60  90]
 [ 40  70 100]]


In [109]:
print('Applying median() function:')

print(np.median(i2)) 


Applying median() function:
60.0


In [110]:
print('Applying median() function across rows:')

print(np.median(i2, axis=1)) 

Applying median() function across rows:
[50. 60. 70.]


In [111]:
print('Applying median() function across columns:')

print(np.median(i2, axis=0))

Applying median() function across columns:
[30. 60. 90.]


# numpy.mean()
Arithmetic mean is the sum of elements along an axis divided by the number of elements. The numpy.mean() function returns the arithmetic mean of elements in the array.

In [113]:
i3 = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print(i3) 

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [114]:
print('Applying mean() function:')

print(np.mean(i3))

Applying mean() function:
3.6666666666666665


In [115]:
print('Applying mean() function along rows:')

print(np.mean(i3, axis = 1))

Applying mean() function along rows:
[2. 4. 5.]


In [116]:
print('Applying mean() function along columns:')

print(np.mean(i3, axis = 0))

Applying mean() function along columns:
[2.66666667 3.66666667 4.66666667]


# numpy.average()
Weighted average is an average resulting from the multiplication of each component by a factor reflecting its importance. The numpy.average() function computes the weighted average of elements in an array according to their respective weight given in another array. The function can have an axis parameter. If the axis is not specified, the array is flattened.

Considering an array [1,2,3,4] and corresponding weights [4,3,2,1], the weighted average is calculated by adding the product of the corresponding elements and dividing the sum by the sum of weights.

Weighted average = (14+23+32+41)/(4+3+2+1)

In [117]:
# declare an array
i4 = np.array([1,2,3,4]) 

# print the array 
print(i4) 

[1 2 3 4]


In [118]:
print('Applying average() function:')

print(np.average(i4))

Applying average() function:
2.5


In [119]:
# specify weights

wts = np.array([4,3,2,1]) 

print('Applying average() function with weights:')

print(np.average(i4,weights = wts))

Applying average() function with weights:
2.0


In [120]:
# Returns the sum of weights, if the returned parameter is set to True.

print('Sum of weights')

print(np.average([1,2,3,4],weights = [4,3,2,1], returned = True))

Sum of weights
(2.0, 10.0)


# Variance
Variance is the average of squared deviations. It is given by mean(abs(x - x.mean())2)**.

In [121]:
# calculation of variance

i5 = np.array([1,2,3,4])

print(np.var(i5))

1.25


In [122]:
# calculate variance of n3

print(np.var(n3))

240.46222222222215


# Standard Deviation
Standard deviation is the square root of the variance.

In [124]:
print(np.std(i5))

1.118033988749895


In [125]:
print(np.std(n3))

15.506844366995567


# NumPy Sorting
NumPy provides various sorting related functions. These sorting functions implement different sorting algorithms and enable us to sort the array as we want. These sorting functions are as follows:-

numpy.sort()
The sort() function returns a sorted copy of the input array. It has the following parameters:−

numpy.sort(a, axis, kind, order)

Description of the parameters is as follows:-

a - Array to be sorted

axis - The axis along which the array is to be sorted. If none, the array is flattened, sorting on the last axis

kind - Default is quicksort

order - If the array contains fields, the order of fields to be sorted

In [126]:
# declare an array
s1 = np.array([[9,4],[2,7]]) 

print('Our array is:')

print(s1)

Our array is:
[[9 4]
 [2 7]]


In [127]:
# sorting along columns, axis = 0

print('Applying sort() function along columns:')

print(np.sort(s1, axis = 0))

Applying sort() function along columns:
[[2 4]
 [9 7]]


# numpy.argsort()
The argsort() function performs an indirect sort on input array, along the given axis and using a specified kind of sort to return the array of indices of data. This indices array is used to construct the sorted array.

In [128]:
s2 = np.array([5,9,2]) 

print('Our array is:')

print(s2) 

Our array is:
[5 9 2]


In [129]:
# applying argsort() to s2

s3 = np.argsort(s2) 

print(s3)


[2 0 1]


In [130]:
# reconstruct original array in sorted order

print(s2[s3]) 


[2 5 9]


# NumPy Searching
NumPy package has a number of functions for searching inside an array. These functions enable us to find the maximum, the minimum as well as the elements satisfying a given condition.

numpy.argmax() and numpy.argmin()
These two functions return the indices of maximum and minimum elements respectively along the given axis.

In [131]:
d1 = np.array([[30,40,70],[80,20,10],[50,90,60]]) 

print('Our array is:')

print(d1) 

Our array is:
[[30 40 70]
 [80 20 10]
 [50 90 60]]


In [132]:
# applying argmax() function to d1

print(np.argmax(d1))

7


In [133]:
# index of maximum number in flattened array

print(d1.flatten())


[30 40 70 80 20 10 50 90 60]


In [134]:
# array containing indices of maximum along axis 0

maxindex = np.argmax(d1, axis = 0)

print(maxindex)


[1 2 0]


In [135]:
# array containing indices of maximum along axis 1

maxindex = np.argmax(d1, axis = 1) 

print(maxindex) 

[2 0 1]


In [136]:
# applying argmin() function to d1

minindex = np.argmin(d1)

print(minindex) 

5


In [137]:
# flattened array

print(d1.flatten()[minindex]) 

10


In [138]:
# flattened array along axis 0

minindex = np.argmin(d1, axis = 0) 

print(minindex)

[0 1 1]


In [139]:
# flattened array along axis 1

minindex = np.argmin(d1, axis = 1)

print(minindex)

[0 2 0]


# numpy.nonzero()
The nonzero() function returns the indices of non-zero elements in the input array.

In [140]:
print('Our array is:')

print(d1) 

Our array is:
[[30 40 70]
 [80 20 10]
 [50 90 60]]


In [141]:
# applying nonzero() function

print(np.nonzero(d1))

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))


In [142]:
# get the indices of non-zero elements 

d1.nonzero()

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [143]:
# get the elements based on above indices

d1[d1.nonzero()]

array([30, 40, 70, 80, 20, 10, 50, 90, 60])

# numpy.where()
The where() function returns the indices of elements in an input array where the given condition is satisfied.

In [144]:
d2 = np.arange(9.).reshape(3, 3) 

print('Our array is:')

print(d2)  

Our array is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [145]:
print('Indices of elements > 3')

d3 = np.where(d2 > 3) 

print(d3)  

Indices of elements > 3
(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))


In [146]:
print('Use these indices to get elements satisfying the condition')


print(d2[d3])

Use these indices to get elements satisfying the condition
[4. 5. 6. 7. 8.]


# numpy.extract()
The extract() function returns the elements satisfying any condition.

In [147]:
e1 = np.arange(9.).reshape(3, 3) 

print('Our array is:')

print(e1)  

Our array is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [148]:
# define a condition 

condition = np.mod(e1,2) == 0 

In [149]:
# evaluate the condition

print('Element-wise value of condition')

print(condition)

Element-wise value of condition
[[ True False  True]
 [False  True False]
 [ True False  True]]


In [150]:
# extract corresponding elements

print('Extract elements using condition')

print(np.extract(condition, e1))

Extract elements using condition
[0. 2. 4. 6. 8.]


# Random sampling with NumPy
NumPy provides random module for doing random sampling. This random module contains many useful functions for generation of random numbers.

There are several functions to generate simple random data. These functions are described below:-

rand()
This function creates an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [152]:
np.random.rand(3,2)

array([[0.88508582, 0.33923188],
       [0.87479188, 0.48550504],
       [0.12165061, 0.93883199]])

# randn()
It returns a sample (or samples) from the "standard normal" distribution.

In [155]:
np.random.randn()

-0.45375331446779826

# randint()
It returns random integers from low (inclusive) to high (exclusive)

In [153]:
np.random.randint(5, size=(2,4))

array([[4, 1, 1, 3],
       [3, 3, 1, 0]])

# random()
It returns random floats in the half-open interval [0.0, 1.0)

In [159]:
np.random.random_sample()

0.10747483975147143

# choice()
It generates a random sample from a given 1-D array.

In [160]:
# generates a uniform random sample from np.arange(5) of size 3

np.random.choice(5, 3)

array([3, 4, 0])

#  Scaler arithemetic
A linear algebric term with a single value

In [162]:
array = np.array([1.56, 2.5, 3.6])


print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)
print(array**5)

[2.56 3.5  4.6 ]
[-0.44  0.5   1.6 ]
[ 4.68  7.5  10.8 ]
[0.39  0.625 0.9  ]
[  9.23895798  97.65625    604.66176   ]


# Vectorized math funs
A Liner algebric term, a single dimesion like 1-d list
Using vectorized math functions we can apply a function to an entire array without using the loop.




In [165]:
# # Gives square root
print(np.sqrt(array))

# # Round the values
print(np.round(array))

# To round down use floor and round up use ceil
print(np.floor(array))
print(np.ceil(array))

# Constants
print(np.pi)

[1.2489996  1.58113883 1.8973666 ]
[2. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]
3.141592653589793
